apiVersion: v1
kind: Pod
metadata:
  name: my-kubernetes-dashboard
spec:
  containers:
    - name: container-name
      image: image-name
  serviceAccount: serviceaccountname
# Not to mount default service account
  automountServiceAccountToken: false