apiVersion: v1
kind: Pod
metadata:
  name: tolerant-pod
spec:
  containers:
    - name: containername
      image: imagename
  tolerations:
    - key: "key1"
      operator: "Equal"
      value: "blue"
      effect: "NoSchedule|PreferNoSchedule|NoExecute  "