apiVersion: v1
kind: Pod
metadata:
  name: resource-allocation-example
spec:
  containers:
    - name: container-name
      image: image-name
      ports:
        - containerPort: 8080
      resources:
        requests:
          memory: "1Gi"
          cpu: 1
        limits:
          memory: "2G"
          cpu: 2