apiVersion: v1
kind: Pod
metadata:
  name: nodeaffinity-pod
spec:
  containers:
    - name: nodaffinitypodnmae
      image: image
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExcecution:
        nodeSelectorTerms:
          - matchExpression:
              - key: size
                operator: In | NotIn | Exists
                values:
                  - Large
                  - Medium
