apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper-pod
spec:
  containers:
    - name: ubuntu-sleeper
      image: ubuntu-sleeper
      # the command field override the entrypoint field in the docker file
      command: ["sleep2.0"]
      # the args field override the CMD field in the docker file
      args: ["10"]
      env: # the possibility to pass environment variable to the container it is list or array of name,value pairs
        - name: key
          value: value
        - name: key1
          value: value1
        - name: key2
          value: value2

